instructor:
  name: "N.N."
  affiliation: "Institution Line"
  affiliation2: "2nd Institution line, if wanted" # may be empty

layout:
  beamertheme: "CambridgeUS" # you can choose any, the slides are tested
                             # with 'CambridgeUS'
  colortheme: "beaver"       # you can choose any, the slides are tested with
                             # 'beaver'
  # choose any preconfigured color or those from the preamble
  beamercolor_structure:  "fg=UniRot" 
  beamercolor_title:      "fg=UniRot"
  beamercolor_title_head: "fg=UniRot"

  beamercolor_block_title: "bg=UniRot!20,fg=darkred"
  beamercolor_block_body:  "fg=black, bg=plightgrey2"

  beamercolor_block_title_alerted: "fg=white,bg=UniRot"
  beamercolor_block_title_example: "fg=white,bg=PineGreen!80"
  
course:
  #title: "" # specifiy your title here, else a default is used. 
  #subtitle: "" # specifiy your subtitle here, else a default is used. 
  date: "datestring" # maybe: "\today"
  # Editors recommendations are a matter of taste and technological
  # setups (e.g. on-demand setups). Hence, specify an editor-slide,
  #  here:
  editorfile: "common/<path to editor tex file>"
  # The next line indicates the slides explaining
  # a condarc file on a cluster, copy and adjust
  # for your cluster.
  condarcfile: "common/<path to condarc file>"
  # these are the path names to contain sample data
  # see the README for explanations.
  pathtosetup: "<path to setup>"
  pathtosolutions: "<path to solutions>"
  # This is the selected slide to explain the 'Hello World' script
  # to introduce SLURM. It requires different account and partition
  # settings on every cluster.
  hello_world_script: "common/<path to hello world slide>"
  #
